version: '3'
services:
  database:
    container_name: postgres-container
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
  server:
    container_name: server-container
    build: .
    image: server-school
    restart: always
    command: npm run start:prod
    volumes:
      - ./dist:/app/dist
    ports:
      - "3001:3001"
    networks:
      - net
    depends_on:
      - database

networks:
  net:
    driver: bridge
